services:
  cai_llama:
    build:
      context: .
    container_name: cai_llama
    shm_size: "40GB"
    volumes:
      - .:/opt/project
    command: /bin/bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]